import type { TourStep } from "./types";

// Build order: Finance is third (see the onboarding-tour plan — Head,
// Assistant, Finance, Registration, HR, Admin). Same deep, scenario-based
// style as Head/Assistant: the user clicks real nav links/buttons himself,
// and every requireRealClick step really writes into his disposable demo
// clone for the rest of the session. Admin-only elements (Add/Remove payee,
// Feature toggles, Monthly report look, Staffing notifications, org-wide
// default) are deliberately never referenced here — Finance can't see them.
export const FINANCE_TOUR: TourStep[] = [
  // ── Categories: the rates everything else calculates from ────────────
  {
    path: "/categories",
    selector: "categories-add-extra",
    title: "Extra-work categories",
    body: "These are the categories a head picks from when logging bonus-worthy extra work — try adding one now.",
    placement: "left",
    requireRealClick: true,
  },
  {
    path: "/categories",
    selector: "categories-label",
    title: "Name it",
    body: "Give the new category a name a head will recognize.",
    placement: "top",
  },
  {
    path: "/categories",
    selector: "categories-rate",
    title: "Set its rate",
    body: "For a number-mode category, this is multiplied by whatever the head enters — e.g. a per-extra-session amount.",
    placement: "top",
  },
  {
    path: "/categories",
    selector: "categories-scope-toggle",
    title: "Pick which course(s) this applies to",
    body: "Per-paper rates, brackets, office-hour rates, and category overrides are all set per course — open this picker to select one or more.",
    placement: "bottom",
    requireRealClick: true,
  },
  {
    path: "/categories",
    selector: "categories-scope-option",
    title: "Select a course",
    body: "Pick one to see (and edit) its rates below. Try selecting one now.",
    placement: "right",
    requireRealClick: true,
  },
  {
    path: "/categories",
    selector: "categories-course-rate",
    title: "Per-paper rate",
    body: "What this course pays an assistant per paper checked — the basis for the \"Per paper\" calc method in Salaries.",
    placement: "top",
  },
  {
    path: "/categories",
    selector: "categories-bracket-pay",
    title: "Average-paper brackets",
    body: "An alternative to a flat per-paper rate — pay a fixed amount once an assistant's average papers checked falls in this range.",
    placement: "top",
  },
  {
    path: "/categories",
    selector: "categories-save",
    title: "Save your changes",
    body: "Nothing above is written until you save — this button appears whenever you have unsaved edits. Press it now.",
    placement: "top",
    requireRealClick: true,
  },

  // ── Settings: the finance-visible half of Organization settings ──────
  {
    path: "/payroll",
    selector: "settings-permission-toggle",
    title: "What heads can see and do",
    body: "Control whether heads see salary amounts in evaluations, and whether they can type amounts directly. Try flipping one — it saves instantly.",
    placement: "left",
    requireRealClick: true,
  },
  {
    path: "/payroll",
    selector: "settings-currency",
    title: "Organization currency",
    body: "Used everywhere money is shown — salaries, evaluations, payslips. Changing it re-labels every amount, it doesn't convert values.",
    placement: "bottom",
  },
  {
    path: "/payroll",
    selector: "settings-staff-picker",
    title: "Default calc method, per person",
    body: "Pick a head or assistant here to set how their pay is worked out by default — a per-line override in Salaries always wins over this.",
    placement: "top",
  },
  {
    path: "/payroll",
    selector: "settings-staff-method",
    title: "Choose their method",
    body: "Per paper, by average-paper category, a flat fixed salary, or a hybrid — pick whichever matches how this person is actually paid.",
    placement: "top",
  },
  {
    path: "/payroll",
    selector: "settings-staff-save",
    title: "Save the default",
    body: "This really saves it for real. Press it now.",
    placement: "top",
    requireRealClick: true,
  },
  {
    path: "/payroll",
    selector: "settings-band-min",
    title: "Traffic light grade bands",
    body: "These org-wide percentage cutoffs decide each student's Green/Yellow/Red status on the Students tab, wherever your courses don't use letter grades.",
    placement: "top",
  },

  // ── Salaries: the core of the role ────────────────────────────────────
  {
    path: "/salaries",
    selector: "salaries-period",
    title: "Pick a payroll period",
    body: "Every salary line, adjustment and release action below applies to whichever month is selected here.",
    placement: "bottom",
  },
  {
    path: "/salaries",
    selector: "salaries-generate",
    title: "Generate a new period",
    body: "Creates salary lines for everyone owed pay that month, based on their calc method and logged work. Payroll runs in arrears, so this defaults to last month.",
    placement: "left",
  },
  {
    path: "/salaries",
    selector: "salaries-row-expand",
    title: "Open a person's breakdown",
    body: "Tap anyone's row to see and edit their per-course adjustments. Try it now.",
    placement: "bottom",
    requireRealClick: true,
  },
  {
    path: "/salaries",
    selector: "salaries-calc-method",
    title: "This line's calc method",
    body: "Override how just this one course-line is calculated — independent of their overall default.",
    placement: "right",
  },
  {
    path: "/salaries",
    selector: "salaries-base",
    title: "Base pay",
    body: "The calculated base for this line — editable directly if something needs a manual correction.",
    placement: "top",
  },
  {
    path: "/salaries",
    selector: "salaries-bonus",
    title: "Bonus",
    body: "Add a bonus for this course this month — pair it with a reason below so it's clear on their payslip.",
    placement: "top",
  },
  {
    path: "/salaries",
    selector: "salaries-deduction",
    title: "Deduction",
    body: "Same idea, subtracted instead — for anything owed back this month.",
    placement: "top",
  },
  {
    path: "/salaries",
    selector: "salaries-eval-toggle",
    title: "Evaluation choices",
    body: "See exactly which extra-work and deduction categories the head picked for this person this month, and adjust them directly if needed.",
    placement: "top",
    requireRealClick: true,
  },
  {
    path: "/salaries",
    selector: "salaries-office-hours",
    title: "Office hours",
    body: "Fixed office hours billed this month for this course, at the rate set in Categories.",
    placement: "top",
  },
  {
    path: "/salaries",
    selector: "salaries-release-row",
    title: "Release their pay",
    body: "Nobody sees anything in My Pay until you release it — this makes their breakdown visible to them. Try it now, it's reversible.",
    placement: "left",
    requireRealClick: true,
  },
  {
    path: "/salaries",
    selector: "salaries-release-all",
    title: "Or release everyone at once",
    body: "Once a period's numbers are final, this releases every unreleased person's pay in one click.",
    placement: "bottom",
  },
  {
    path: "/salaries",
    selector: "salaries-mark-paid",
    title: "Mark as paid",
    body: "Once you've actually paid someone, mark it here — try it now, you can attach a receipt or skip that.",
    placement: "left",
    requireRealClick: true,
  },
  {
    path: "/salaries",
    selector: "salaries-mark-paid-confirm",
    title: "Confirm",
    body: "This really marks them as paid for this period. Press it now.",
    placement: "top",
    requireRealClick: true,
  },
  {
    path: "/salaries",
    selector: "salaries-messages",
    title: "Salary inquiries",
    body: "If someone messages you about their pay, it shows up here — reply straight from this thread. Open it now.",
    placement: "left",
    requireRealClick: true,
  },
  {
    path: "/salaries",
    selector: "salaries-messages-input",
    title: "Write a reply",
    body: "Type your reply here.",
    placement: "top",
  },
  {
    path: "/salaries",
    selector: "salaries-messages-send",
    title: "Send it",
    body: "This really posts your reply to the thread. Feel free to send one for real.",
    placement: "top",
  },

  // ── Payments: every head & assistant's payment setup at a glance ─────
  {
    path: "/payments",
    selector: "payments-search",
    title: "Find someone",
    body: "Search across every head and assistant in the organization.",
    placement: "bottom",
  },
  {
    path: "/payments",
    selector: "payments-filter-assistant",
    title: "Filter by role",
    body: "Narrow the list to just heads or just assistants. Try it now.",
    placement: "bottom",
    requireRealClick: true,
  },
  {
    path: "/payments",
    selector: "payments-calc-method",
    title: "Their calc method",
    body: "The same default you can set from Settings, editable right here per person too.",
    placement: "top",
  },
  {
    path: "/payments",
    selector: "payments-pay-method",
    title: "How they're paid",
    body: "Bank transfer, mobile wallet, or InstaPay — shown alongside their salary breakdown wherever it appears.",
    placement: "top",
  },
  {
    path: "/payments",
    selector: "payments-bonus-pct",
    title: "Standing bonus %",
    body: "An automatic percentage bonus applied to this person's pay every period, on top of anything a head adds manually.",
    placement: "top",
  },

  // ── Evaluations: read-only view into what heads submitted ─────────────
  {
    path: "/evaluations",
    selector: "evaluations-period",
    title: "Every evaluation a head has submitted",
    body: "Filter by month, course or assistant to see exactly what a head chose — extras, deductions, rating and notes, read-only here.",
    placement: "bottom",
  },
  {
    path: "/evaluations",
    selector: "evaluations-row-expand",
    title: "See the full detail",
    body: "Open a row to see every line item behind the totals. To change a payable amount, that happens in Salaries instead. Try it now.",
    placement: "bottom",
    requireRealClick: true,
  },

  // ── Chat: staff DMs only — no course channels for Finance ─────────────
  {
    path: "/chat",
    selector: "chat-new-message",
    title: "Start a conversation",
    body: "Finance doesn't have course channels — every conversation here is a direct message with another staff member. Press this now.",
    placement: "bottom",
    requireRealClick: true,
  },
  {
    path: "/chat",
    selector: "chat-dm-directory-row",
    title: "Pick a coworker",
    body: "Every head, assistant, and fellow staff member in the organization shows up here. Pick one to start messaging them.",
    placement: "right",
    requireRealClick: true,
  },
  {
    path: "/chat",
    selector: "chat-message-input",
    title: "Say something",
    body: "Type a message here — Enter sends it, Shift+Enter makes a new line.",
    placement: "top",
  },
  {
    path: "/chat",
    selector: "chat-send",
    title: "Send it",
    body: "This really posts to the conversation — try sending a message if you'd like.",
    placement: "top",
  },

  // ── Settings: password + theme ────────────────────────────────────────
  {
    path: "/chat",
    selector: "user-menu-toggle",
    title: "Your account menu",
    body: "Everything account-related — your settings and light/dark mode — lives behind your avatar, top right. Open it now.",
    placement: "left",
    requireRealClick: true,
  },
  {
    path: "/chat",
    selector: "theme-toggle",
    title: "Light or dark mode",
    body: "Switch the whole app's theme right from here. Try it now.",
    placement: "left",
    requireRealClick: true,
  },
  {
    path: "/settings",
    selector: "settings-password-section",
    title: "Changing your password",
    body: "And this is where you'd update your password any time — your name, avatar, and email are also managed on this page. That wraps up the tour!",
    placement: "top",
  },
];
