import type { CSSProperties } from "react";
import {
  LayoutDashboard,
  Users,
  UserCheck,
  UserPlus,
  ClipboardList,
  GraduationCap,
  Wallet,
  CreditCard,
  MessageSquare,
  Search,
  Bell,
  Settings,
  Upload,
  FileUp,
  LogOut,
  Building2,
  Palette,
  Shield,
  BarChart3,
  BookOpen,
  CalendarCheck,
  Menu,
  Send,
  Filter,
  Mail,
  Minus,
  ChevronDown,
  TrendingUp,
  Inbox,
  Clock,
  Check,
  CheckCheck,
  AlertCircle,
  X,
  Plus,
  Phone,
  Sun,
  Moon,
  ChevronRight,
  ChevronLeft,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  Eye,
  EyeOff,
  Target,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  dashboard: LayoutDashboard,
  users: Users,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "clipboard-list": ClipboardList,
  grad: GraduationCap,
  wallet: Wallet,
  card: CreditCard,
  message: MessageSquare,
  search: Search,
  bell: Bell,
  settings: Settings,
  upload: Upload,
  "file-up": FileUp,
  logout: LogOut,
  building: Building2,
  palette: Palette,
  shield: Shield,
  chart: BarChart3,
  book: BookOpen,
  "cal-check": CalendarCheck,
  menu: Menu,
  send: Send,
  filter: Filter,
  mail: Mail,
  minus: Minus,
  "chevron-down": ChevronDown,
  trend: TrendingUp,
  inbox: Inbox,
  clock: Clock,
  check: Check,
  check2: CheckCheck,
  alert: AlertCircle,
  x: X,
  plus: Plus,
  phone: Phone,
  sun: Sun,
  moon: Moon,
  cr: ChevronRight,
  "chev-left": ChevronLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-r": ArrowRight,
  eye: Eye,
  "eye-off": EyeOff,
  target: Target,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 18,
  className,
  style,
}: {
  name: IconName;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Cmp = ICONS[name];
  return <Cmp size={size} strokeWidth={2} className={className} style={style} />;
}
